### ISSUE TITLE
boolean input string not 'raw'

### ISSUE THREAD

**Issue by pehrlich** [joelmoss/dynamic_form#6]
displays as string, rather than rendered html:
```<select id="account_is_chef" name="account[is_chef]"><option value="false">False</option><option value="true">True</option></select> 

```
```

**Comment by devdatta** [comment]
Can you please elaborate a little bit more?

**Comment by pehrlich** [comment]
Hey!

Here's a snippet from my edit page:

<% cols = @account.class.column_names %>

```
<% cols.each do |col| %>
    <br/><b><%= f.label col.to_sym %></b>:
    <%= input 'account', col %>
<% end %>
```

Here's the model:

> Account
>  => Account( <snip>, is_chef: boolean)

When the page is rendered, all fields are displayed correctly except for
this one (the only boolean), which appears as the source of a True/False
select menu printed out on the page.  (Code eaten by github).

Haven't had the time for exhaustive testing yet, or would be digging in to
the source of this delicious gem myself :-)

Cheers & Thanks,
--Peter

**Comment by devdatta** [comment]
I have fixed the issue. Please let me know if it still causes any problem.

Cheers,
Devdatta
