### ISSUE TITLE
error_messages_for is escaping html

### ISSUE THREAD

**Issue by exceptionraiser** [joelmoss/dynamic_form#8]
I'm using error_messages_for on my forms but it's escaping the html like so: http://cl.ly/DlDN

This is the code I'm using: 

```
<%= error_messages_for(:form, :user, :message => "<strong>Opps, it doesn't look like you filled everything out properly.</strong><br>
            The fields marked in RED below must be filled out properly before you can continue.") %>
```

Anything I'm missing to get this to work properly? As you can see the input fields with the `fieldWithErrors` is also escaping html for some reason.

Thanks!

**Comment by joelmoss** [comment]
That is a feature of Rails as a way of ensuring any injected HTML is safe. Pass the HTML to the `raw()` method like this:

```
<%= error_messages_for :form, :user, :message => raw("<strong>Opps, it doesn't look like you filled everything out properly.</strong><br>The fields marked in RED below must be filled out properly before you can continue.") %>
```

**Comment by exceptionraiser** [comment]
Thanks Joel!
